FIX: use `PluginSignature` instead of `Signature` from `nu_protocol` (#3)
This PR fixes
```
error[E0053]: method `signature` has an incompatible type for trait
  --> src/main.rs:71:28
   |
71 |     fn signature(&self) -> Vec<Signature> {
   |                            ^^^^^^^^^^^^^^
   |                            |
   |                            expected struct `PluginSignature`, found struct `nu_protocol::Signature`
   |                            help: change the output type to match the trait: `Vec<PluginSignature>`
   |
   = note: expected fn pointer `fn(&StrLen) -> Vec<PluginSignature>`
              found fn pointer `fn(&StrLen) -> Vec<nu_protocol::Signature>`

For more information about this error, try `rustc --explain E0053`.
error: could not compile `nu_plugin_len` due to previous error
```
that comes with the new `nu_protocol::PluginSignature` in replacement
for `nu_protocol::Signature`